CREATE TABLE `jars_monitor_panel_config` (
  `id`               bigint(20)   NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `device`           varchar(100) NOT NULL DEFAULT 'All' COMMENT '设备标识（All=全部设备）',
  `category`         varchar(100) NOT NULL DEFAULT 'All' COMMENT 'Jar应用分类（All=全部分类）',
  `app_name`         varchar(200) NOT NULL DEFAULT 'All' COMMENT 'Jar应用名（All=全部应用）',
  `panel_key`        varchar(100) NOT NULL COMMENT '面板唯一标识（default_1 / custom_xxx）',
  `panel_name`       varchar(200) NOT NULL COMMENT '面板显示名称',
  `is_custom`        tinyint(1)   NOT NULL DEFAULT 0 COMMENT '0=默认面板 1=自定义面板',
  `grafana_panel_id` int(11)               DEFAULT NULL COMMENT 'Grafana PanelID，仅默认面板使用',
  `promql`           text                  DEFAULT NULL COMMENT 'PromQL，仅自定义面板使用',
  `chart_type`       varchar(20)           DEFAULT 'graph' COMMENT '图表类型',
  `unit`             varchar(20)           DEFAULT 'none'  COMMENT '数值单位',
  `time_range`       varchar(10)           DEFAULT '5m'    COMMENT '时间范围',
  `refresh_interval` varchar(10)           DEFAULT '30s'   COMMENT '刷新间隔（空=不刷新）',
  `scope`            varchar(20)           DEFAULT 'app'   COMMENT '生效范围 app/category/device/global',
  `sort_order`       int(11)               DEFAULT 0       COMMENT '排列顺序',
  `description`      text                  DEFAULT NULL    COMMENT '指标描述（含义、作用、异常场景等）',
  `remark`           varchar(500)          DEFAULT NULL    COMMENT '备注',
  `create_by`        varchar(64)           DEFAULT ''      COMMENT '创建者',
  `create_time`      datetime              DEFAULT NULL    COMMENT '创建时间',
  `update_by`        varchar(64)           DEFAULT ''      COMMENT '更新者',
  `update_time`      datetime              DEFAULT NULL    COMMENT '更新时间',
  `del_flag`         char(1)               DEFAULT '0'     COMMENT '删除标志（0=正常 2=删除）',
  PRIMARY KEY (`id`),
  KEY `idx_device_category_app` (`device`, `category`, `app_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Jars应用监控面板配置';