DROP TABLE IF EXISTS `jars_app_manager`;
CREATE TABLE `jars_app_manager` (
  `jars_id`          bigint(20)    NOT NULL AUTO_INCREMENT          COMMENT 'JAR应用ID',
  `device_id`        bigint(20)    DEFAULT NULL                     COMMENT '所属设备ID（关联device_manager表）',
  `app_name`         varchar(200)  NOT NULL                         COMMENT 'JAR应用名称',
  `category`         varchar(100)  DEFAULT 'default'                COMMENT '应用分类（如: web, scheduler, gateway等）',
  `status`           tinyint(1)    NOT NULL DEFAULT 0               COMMENT '应用状态（0=正常 1=禁用）',
  `ip_address`       varchar(128)  NOT NULL                         COMMENT '部署主机IP地址',
  `port`             varchar(10)   NOT NULL                         COMMENT '应用监听端口',
  `metrics_port`     varchar(10)   DEFAULT NULL                     COMMENT 'JMX/Metrics暴露端口（Prometheus抓取用）',
  `metrics_path`     varchar(200)  DEFAULT NULL  COMMENT 'Metrics路径',
  `jvm_args`         varchar(500)  DEFAULT NULL                     COMMENT 'JVM启动参数备注',
  `deploy_path`      varchar(500)  DEFAULT NULL                     COMMENT 'JAR包部署路径',
  `java_version`     varchar(20)   DEFAULT NULL                     COMMENT 'Java版本（如: 1.8, 11, 17）',
  `leader`           varchar(64)   DEFAULT NULL                     COMMENT '负责人',
  `remark`           varchar(500)  DEFAULT NULL                     COMMENT '备注',
  `create_by`        varchar(64)   DEFAULT ''                       COMMENT '创建者',
  `create_time`      datetime      DEFAULT NULL                     COMMENT '创建时间',
  `update_by`        varchar(64)   DEFAULT ''                       COMMENT '更新者',
  `update_time`      datetime      DEFAULT NULL                     COMMENT '更新时间',
  PRIMARY KEY (`jars_id`),
  KEY `idx_device_id` (`device_id`),
  KEY `idx_app_name` (`app_name`),
  KEY `idx_category` (`category`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='JAR应用管理表（手动注册，非K8s Pod）';